### ISSUE TITLE
ReadFFMpeg decoder stalls

### ISSUE THREAD

**Issue by skoulik** [MrKepzie/openfx-io#14]
Hi,
On windows, I often observe message: "ReadFFMpeg1: error: FFmpeg Reader detected decoding stall, possible file corruption". More often (but not always) this happens at the end of the video on last 3-7 frames.
After the exception, the reader cannot recover and decode new frames even when you try to seek back to frames that were decoded correctly previously.
The problem happens when running Natron with IO.ofx.bundle shipped with Natron. The same problem happens on IO.ofx.bundle build from current HEAD (with VS2013, 64bit, all dependencies static).
FFMpeg itself when running from command line extracts the frames without problems.

One of the videos to reproduce the problem: http://techslides.com/demos/sample-videos/small.mp4

**Comment by devernay** [comment]
Hi,
closed by https://github.com/MrKepzie/openfx-io/commit/5ad3916fa80ce6650de1b57bf56e64d43cac3c74 .
nightly builds should include this fix

**Comment by skoulik** [comment]
Hi,
Works perfectly now, thank you!
