### ISSUE TITLE
FFmpeg Reader failed to find timing reference frame

### ISSUE THREAD

**Issue by skoulik** [MrKepzie/openfx-io#15]
Hi,
This is a follow-up of https://github.com/MrKepzie/openfx-io/issues/14
There is another video sample that produces unrecoverable error, but different from the previous one.
http://www.neatvideo.com/files3/testkit.zip

Tested on 6834972c004c394a8bbea9665f6272a1ce95da59

**Comment by MrKepzie** [comment]
Seems to work fine here, do you still have the same problem ? If so on which platform ?

**Comment by skoulik** [comment]
I've just checked on 643f2c8d1cf2fe926534abe11267edd6aa5f2a9f, the issue is still reproducible on Windows 7, 64 bit.
Also reproducible with Natron 1.1 64 bit for windows: Add the clip to the graph with a Reader and cycle through the first 2-4 frames, you'll see the error message. The preview is black.
With Natron 1.2.1 64 bit for windows the issue us still there, but the error message is not persistent, I can see it flashing for a moment when I cycle through the first 10 frames. The preview is black.

**Comment by MrKepzie** [comment]
Have you tried using the snapshots of Natron 2.0 ?
It’s currently building but binaries should be back online for windows in about an hour.

**Comment by skoulik** [comment]
Unfortunately, I am not building Natron.
Here is a trace captured with 
#define TRACE_DECODE_PROCESS 1
#define TRACE_FILE_OPEN 1
hope, this helps
  1 streams:
    FFmpeg stream index 0: Video decoder "mpeg1video" opened ok, getting stream properties:
      Timebase=1/90000 s/tick
      Duration=212400 ticks, 2.36 s
      BitDepth=4
      NumberOfComponents=3
      Framerate=25/1, 25 fps
      Image size=1280x720
      Aspect ratio (from codec)=1
      Determining stream start PTS:
        Obtained from AVStream::start_time=41667 ticks, 0.462967 s
      Determining stream frame count:
        Obtained from AVFormatContext::duration & framerate=59
  1 streams:
    FFmpeg stream index 0: Video decoder "mpeg1video" opened ok, getting stream properties:
      Timebase=1/90000 s/tick
      Duration=212400 ticks, 2.36 s
      BitDepth=4
      NumberOfComponents=3
      Framerate=25/1, 25 fps
      Image size=1280x720
      Aspect ratio (from codec)=1
      Determining stream start PTS:
        Obtained from AVStream::start_time=41667 ticks, 0.462967 s
      Determining stream frame count:
        Obtained from AVFormatContext::duration & framerate=59
  1 streams:
    FFmpeg stream index 0: Video decoder "mpeg1video" opened ok, getting stream properties:
      Timebase=1/90000 s/tick
      Duration=212400 ticks, 2.36 s
      BitDepth=4
      NumberOfComponents=3
      Framerate=25/1, 25 fps
      Image size=1280x720
      Aspect ratio (from codec)=1
      Determining stream start PTS:
        Obtained from AVStream::start_time=41667 ticks, 0.462967 s
      Determining stream frame count:
        Obtained from AVFormatContext::duration & framerate=59
  1 streams:
    FFmpeg stream index 0: Video decoder "mpeg1video" opened ok, getting stream properties:
      Timebase=1/90000 s/tick
      Duration=212400 ticks, 2.36 s
      BitDepth=4
      NumberOfComponents=3
      Framerate=25/1, 25 fps
      Image size=1280x720
      Aspect ratio (from codec)=1
      Determining stream start PTS:
        Obtained from AVStream::start_time=41667 ticks, 0.462967 s
      Determining stream frame count:
        Obtained from AVFormatContext::duration & framerate=59
mov64Reader=00000000056880A0::decode(): frame=0, videoStream=0, streamIdx=0
  Next frame expected out=-1, Seeking to desired frame
  Next frame expected in=unknown, Read OK, Packet data:
    PTS=52467, DTS=41667, Duration=3600, KeyFrame=0, Corrupt=0, StreamIdx=0, PktSize=137744, Relevant stream
    In seek (0), landing frame not found (landed after target at 3), can't seek before start, PTSs present,  giving up
!!ERROR: FFmpeg Reader failed to find timing reference frame, possible file corruption
<-validPicture=0 for frame 0

**Comment by MrKepzie** [comment]
Natron 2 binaries are released as snapshots at every commit, see https://natron.inria.fr/snapshots/

**Comment by skoulik** [comment]
Tried Natron-03a73abe1eeeda2d178436f649df278d4a5677c7 for Windows 64 bit. The preview/playback or readers seem to be broken. Only first frame of the videos is displayed on preview. Preview does not refresh when I move cursor throu the timeline. Reproducible on any video I've tried, not only the one mentioned above.

**Comment by devernay** [comment]
see also https://github.com/MrKepzie/Natron/issues/1244

**Comment by devernay** [comment]
see https://github.com/devernay/ffplay
