### ISSUE TITLE
 MS Windows pre-compiled static binaries for dependencies doesn't exists

### ISSUE THREAD

**Issue by abushinov** [MrKepzie/openfx-io#16]
Compiling on MS Windows
We provide pre-compiled static binaries for dependencies here:
https://www.dropbox.com/s/s5yuh9k3kum99jp/3rdparty_windows_32_and_64bits_msvc2010.zip

**Comment by MrKepzie** [comment]
Hi, they have moved onto source forge:

https://sourceforge.net/projects/natron/files/Natron_Windows_3rdParty.zip/download <https://sourceforge.net/projects/natron/files/Natron_Windows_3rdParty.zip/download>

**Comment by abushinov** [comment]
Thank you.
