### ISSUE TITLE
single-channel PNG are Y and two-channel PNG images are Y+A, and should thus be read as RGB/RGBA

### ISSUE THREAD

**Issue by devernay** [MrKepzie/openfx-io#24]
see the PNG spec.
Very often, image editing or conversion programs write RGBA images as YA when R=G=B.
Same happens when writing RGB images, which may result in single-channel images.

As  result, a PNG image sequence may contain RGB and Y images, or RGBA and Y+A images.

This bug was already encountered in the past.

**Comment by MrKepzie** [comment]
Fixed in https://github.com/MrKepzie/openfx-io/commit/d14ea2c14f0f1e187a882e567a8a92000de4a288

**Comment by devernay** [comment]
reopening. single-channel images are RGB
https://www.w3.org/TR/PNG/#4Concepts.RGBMerging

**Comment by devernay** [comment]
and RGBA images with alpha set to the max value may also be compacted as RGB, so the PNG reader should only output RGBA, or there may be differences in components along a sequence.

- let's say a RGBA sequence begins with a black and transparent image-> it gets encoded as Y+A
- then appears color, and it is half-transparent -> it gets encoded as RGBA
- then it becomes completely opaque -> RGB
- then there is a white and opaque image -> Y

all this is along the same RGBA sequence.
For consistency, everything should be output as RGBA, and the user may use a shuffle afterwards to select just the alpha.

**Comment by devernay** [comment]
to test PNG reading, use: http://www.schaik.com/pngsuite/

**Comment by devernay** [comment]
fixed by https://github.com/MrKepzie/openfx-io/commit/9e7aae92e9c4489f9304e8d3c5a5d1682fc9f805
