### ISSUE TITLE
../OIIO/OIIOText.cpp:558:26: error: ‘DBL_MAX’ was not declared in this scope

### ISSUE THREAD

**Issue by livingBEEF** [MrKepzie/openfx-io#25]
Unless the error was caused by my own incompetence, might be something you'd want to know about.
I got it to work by adding `#include <cfloat>` line at the top. 
commit  2b3098b, `make CONFIG=release` on Gentoo linux with gcc-4.9.3, glibc-2.22

**Comment by devernay** [comment]
thanks
