### ISSUE TITLE
Include submodules in tarball release

### ISSUE THREAD

**Issue by theSoenke** [MrKepzie/openfx-io#29]
It would be great if release tarball could be provided which contains all submodules and header files like tinydir.h. Would make it a lot easier to package and make it reproducible

Thanks

**Comment by olear** [comment]
I updated the Natron release with tarballs for the nodes.

https://github.com/MrKepzie/Natron/releases/2.1.9

**Comment by theSoenke** [comment]
Awesome 👍 👏

**Comment by devernay** [comment]
@olear can you share the recipe to make these, so that we do the same at each release ?
a shell script that takes the release number as arg would be super cool.

**Comment by olear** [comment]
Ok, I will make a tarball release script.

**Comment by theSoenke** [comment]
@olear Any progress on the release script? Would be great if you could again publish the release tarballs for the latest version

**Comment by theSoenke** [comment]
@devernay @olear It would help me a lot when you could provide full release tarball for the newest versions
