### ISSUE TITLE
Building with imagemagick 7 fails

### ISSUE THREAD

**Issue by theSoenke** [MrKepzie/openfx-io#30]
The current release 2.1.9 seems to be not compatible with imagemagick 7.0.3

`../Magick/Sketch.cpp:199:39: error: 'CopyOpacityCompositeOp' is not a member of 'Magick'
         output.composite(image, 0, 0, Magick::CopyOpacityCompositeOp);`

**Comment by olear** [comment]
Wrong repository. Add IM=7 when building openfx-arena.

**Comment by theSoenke** [comment]
Ups. But thanks IM=7 solved this
